const OPENSCOUT_SUPPORTED_ROOT_DOMAINS = [
    "abt.com",
    "academy.com",
    "acehardware.com",
    "adidas.com",
    "adorama.com",
    "advanceautoparts.com",
    "ae.com",
    "aerie.com",
    "alibaba.com",
    "aliexpress.com",
    "allmodern.com",
    "aloyoga.com",
    "amazon.com",
    "anthropologie.com",
    "apple.com",
    "arcteryx.com",
    "ashleyfurniture.com",
    "asics.com",
    "asos.com",
    "athleta.com",
    "americantrucks.com",
    "autoanything.com",
    "backcountry.com",
    "backmarket.com",
    "barnesandnoble.com",
    "bedbathandbeyond.com",
    "bestbuy.com",
    "bhphotovideo.com",
    "birchlane.com",
    "bloomingdales.com",
    "bollandbranch.com",
    "bonobos.com",
    "booksamillion.com",
    "brooksbrothers.com",
    "fergusonhome.com",
    "burton.com",
    "calvinklein.us",
    "carhartt.com",
    "carparts.com",
    "cb2.com", 
    "cdw.com",
    "champssports.com",
    "chewy.com",
    "clinique.com",
    "colourpop.com",
    "columbia.com",
    "containerstore.com",
    "converse.com",
    "crateandbarrel.com",
    "crocs.com",
    "crutchfield.com",
    "cvs.com",
    "dell.com",
    "dermstore.com",
    "dickssportinggoods.com",
    "dillards.com",
    "dsw.com",
    "duluthtrading.com",
    "ebay.com",
    "eddiebauer.com",
    "esteelauder.com",
    "etsy.com",
    "everlane.com",
    "evo.com",
    "express.com",
    "famousfootwear.com",
    "farfetch.com",
    "fashionnova.com",
    "fentybeauty.com",
    "finishline.com",
    "flightclub.com",
    "footlocker.com",
    "forever21.com",
    "freepeople.com",
    "gamestop.com",
    "gap.com",
    "glossier.com",
    "gnc.com",
    "guitarcenter.com",
    "hm.com",
    "hollisterco.com", 
    "homedepot.com",
    "hp.com",
    "hsn.com",
    "hydroflask.com",
    "iherb.com",
    "ikea.com",
    "jcpenney.com",
    "jcrew.com",
    "joann.com",
    "journeys.com",
    "kiehls.com",
    "kohls.com",
    "landsend.com",
    "lanebryant.com",
    "lego.com",
    "lenovo.com",
    "levi.com",
    "llbean.com",
    "lowes.com",
    "lululemon.com",
    "lulus.com",
    "lush.com",
    "maccosmetics.com",
    "macys.com",
    "madewell.com",
    "marmot.com",
    "mercari.com",
    "michaels.com",
    "microcenter.com",
    "microsoft.com",
    "monoprice.com",
    "newbalance.com",
    "newegg.com",
    "nike.com",
    "nintendo.com",
    "nordstrom.com",
    "northerntool.com",
    "oldnavy.com",
    "oreillyauto.com",
    "outdoorvoices.com",
    "overstock.com",
    "patagonia.com",
    "petco.com",
    "playstation.com",
    "poshmark.com",
    "potterybarn.com",
    "powells.com",
    "puma.com",
    "qvc.com",
    "ralphlauren.com",
    "raymourflanigan.com",
    "reebok.com",
    "rei.com",
    "revolve.com",
    "roomstogo.com",
    "ruggable.com",
    "rugsusa.com",
    "sallybeauty.com",
    "samsung.com",
    "scheels.com",
    "sephora.com",
    "serenaandlily.com",
    "shein.com",
    "shoecarnival.com",
    "shopbop.com",
    "skechers.com",
    "sony.com",
    "target.com",
    "temu.com",
    "thebodyshop.com",
    "thenorthface.com",
    "thriftbooks.com",
    "ulta.com",
    "uncommongoods.com",
    "underarmour.com",
    "uniqlo.com",
    "untuckit.com",
    "vans.com",
    "victoriassecret.com",
    "vitaminshoppe.com",
    "walgreens.com",
    "walmart.com",
    "wayfair.com",
    "westelm.com",
    "wish.com",
    "worldmarket.com",
    "wrangler.com",
    "yeti.com",
    "zappos.com",
    "zara.com",
];

const OPENSCOUT_DOMAIN_SET = new Set(
    OPENSCOUT_SUPPORTED_ROOT_DOMAINS.filter(Boolean).map((d) => d.toLowerCase())
);

/** @param {string} hostname */
function normalizeHostname(hostname) {
    return (hostname || "").toLowerCase().replace(/^www\./, "");
}

class SupportedSites {
    static isAllowedHostname(hostname) {
        const host = normalizeHostname(hostname);
        if (!host) {
            return false;
        }
        for (const root of OPENSCOUT_DOMAIN_SET) {
            if (host === root || host.endsWith(`.${root}`)) {
                return true;
            }
        }
        return false;
    }

    static isCurrentSiteSupported() {
        return SupportedSites.isAllowedHostname(window.location.hostname);
    }

    /** Chrome content_script / host_permission match patterns */
    static manifestMatchPatterns() {
        const patterns = [];
        for (const root of OPENSCOUT_DOMAIN_SET) {
            patterns.push(`*://*.${root}/*`, `*://${root}/*`);
        }
        return patterns;
    }
}
